-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 22:40:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_turismo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_turismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_turismo` DEFAULT CHARACTER SET utf8 ;
USE `db_turismo` ;

-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_agencia` (
  `agencia_id` INT NOT NULL AUTO_INCREMENT,
  `agencia_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`agencia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_pasajero` (
  `pasajero_id` INT NOT NULL AUTO_INCREMENT,
  `pasajero_nombre` VARCHAR(100) NOT NULL,
  `pasajero_apellido` VARCHAR(255) NOT NULL,
  `pasajero_documento_identidad` VARCHAR(50) NULL,
  `pasajero_email` VARCHAR(50) NULL,
  `pasajer_fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`pasajero_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_vehiculo` (
  `vehiculo_id` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_placa` VARCHAR(45) NOT NULL,
  `vehiculo_tipo` VARCHAR(45) NOT NULL,
  `vehiculo_stock` INT NOT NULL,
  PRIMARY KEY (`vehiculo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_horario` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `horario_dia` VARCHAR(45) NOT NULL,
  `horario_salida` TIME NULL,
  `horario_retorno` TIME NULL,
  PRIMARY KEY (`horario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_circuito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_circuito` (
  `circuito_id` INT NOT NULL AUTO_INCREMENT,
  `circuito_nombre` VARCHAR(255) NOT NULL,
  `circuito_costo_soles` DOUBLE NOT NULL,
  `circuito_costo_dolares` DOUBLE NOT NULL,
  `circuito_nro_dias` INT NOT NULL,
  `circuito_nro_noches` INT NOT NULL,
  `circuito_alojamiento` TINYINT(1) NOT NULL,
  `circuito_alimentacion` TINYINT(1) NOT NULL,
  `agencia_id` INT NOT NULL,
  PRIMARY KEY (`circuito_id`),
  CONSTRAINT `fk_tbl_circuito_tbl_agencia`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `db_turismo`.`tbl_agencia` (`agencia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_parada` (
  `parada_id` INT NOT NULL AUTO_INCREMENT,
  `parada_nombre` VARCHAR(255) NOT NULL,
  `parada_imagen` VARCHAR(255) NOT NULL,
  `tbl_circuito_circuito_id` INT NOT NULL,
  PRIMARY KEY (`parada_id`),
  CONSTRAINT `fk_tbl_parada_tbl_circuito1`
    FOREIGN KEY (`tbl_circuito_circuito_id`)
    REFERENCES `db_turismo`.`tbl_circuito` (`circuito_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_viaje` (
  `viaje_id` INT NOT NULL AUTO_INCREMENT,
  `viaje_fecha` DATE NOT NULL,
  `tbl_vehiculo_vehiculo_id` INT NOT NULL,
  `tbl_horario_horario_id` INT NOT NULL,
  `tbl_circuito_circuito_id` INT NOT NULL,
  PRIMARY KEY (`viaje_id`),
  CONSTRAINT `fk_tbl_viaje_tbl_vehiculo1`
    FOREIGN KEY (`tbl_vehiculo_vehiculo_id`)
    REFERENCES `db_turismo`.`tbl_vehiculo` (`vehiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_viaje_tbl_horario1`
    FOREIGN KEY (`tbl_horario_horario_id`)
    REFERENCES `db_turismo`.`tbl_horario` (`horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_viaje_tbl_circuito1`
    FOREIGN KEY (`tbl_circuito_circuito_id`)
    REFERENCES `db_turismo`.`tbl_circuito` (`circuito_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_turismo`.`tbl_viaje_pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_turismo`.`tbl_viaje_pasajero` (
  `viaje_pasajero_id` INT NOT NULL AUTO_INCREMENT,
  `viaje_pasajero_monto_pagado` DOUBLE NOT NULL,
  `viaje_pasajero_tipo_moneda` VARCHAR(45) NOT NULL,
  `viaje_pasajero_forma_pago` VARCHAR(45) NOT NULL,
  `tbl_viaje_viaje_id` INT NOT NULL,
  `tbl_pasajero_pasajero_id` INT NOT NULL,
  PRIMARY KEY (`viaje_pasajero_id`),
  CONSTRAINT `fk_tbl_viaje_pasajero_tbl_viaje1`
    FOREIGN KEY (`tbl_viaje_viaje_id`)
    REFERENCES `db_turismo`.`tbl_viaje` (`viaje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_viaje_pasajero_tbl_pasajero1`
    FOREIGN KEY (`tbl_pasajero_pasajero_id`)
    REFERENCES `db_turismo`.`tbl_pasajero` (`pasajero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
