-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 22:35:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_movilidad_escolar
-- -----------------------------------------------------
-- base de datos de movilidad escolar

-- -----------------------------------------------------
-- Schema db_movilidad_escolar
--
-- base de datos de movilidad escolar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_movilidad_escolar` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_movilidad_escolar` ;

-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`tbl_colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`tbl_colegio` (
  `colegio_id` INT NOT NULL AUTO_INCREMENT,
  `colegio_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`colegio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`tbl_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`tbl_alumno` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `alumno_nombre` VARCHAR(255) NOT NULL,
  `alumno_apellido` VARCHAR(255) NOT NULL,
  `alumno_fecha_nacimiento` DATE NULL,
  `alumno_foto` VARCHAR(255) NULL,
  PRIMARY KEY (`alumno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`tbl_grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`tbl_grado` (
  `grado_id` INT NOT NULL AUTO_INCREMENT,
  `grado_nombre` VARCHAR(50) NOT NULL,
  `grado_nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`grado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`tbl_parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`tbl_parentesco` (
  `parentesco_id` INT NOT NULL AUTO_INCREMENT,
  `parentesco_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`parentesco_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`tbl_apoderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`tbl_apoderado` (
  `apoderado_id` INT NOT NULL AUTO_INCREMENT,
  `apoderado_nombre` VARCHAR(255) NOT NULL,
  `apoderado_apellido` VARCHAR(255) NOT NULL,
  `apoderado_telefono` VARCHAR(255) NOT NULL,
  `apoderado_documento_identidad` VARCHAR(20) NULL,
  `parentesco_id` INT NOT NULL,
  PRIMARY KEY (`apoderado_id`),
  CONSTRAINT `fk_tbl_apoderado_tbl_parentesco`
    FOREIGN KEY (`parentesco_id`)
    REFERENCES `db_movilidad_escolar`.`tbl_parentesco` (`parentesco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`tbl_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`tbl_vehiculo` (
  `vehiculo_id` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_placa` VARCHAR(20) NOT NULL,
  `vehiculo_conductor` VARCHAR(255) NULL,
  PRIMARY KEY (`vehiculo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movilidad_escolar`.`movilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movilidad_escolar`.`movilidad` (
  `movilidad_id` INT NOT NULL AUTO_INCREMENT,
  `movilidad_tipo_servicio` VARCHAR(45) NOT NULL,
  `movilidad_turno` VARCHAR(45) NOT NULL,
  `movilidad_seccion` VARCHAR(45) NOT NULL,
  `movilidad_docente` VARCHAR(255) NOT NULL,
  `movilidad_pago` DOUBLE NOT NULL DEFAULT 0,
  `colegio_id` INT NOT NULL,
  `apoderado_id` INT NOT NULL,
  `grado_id` INT NOT NULL,
  `vehiculo_id` INT NOT NULL,
  `alumno_id` INT NOT NULL,
  PRIMARY KEY (`movilidad_id`),
  CONSTRAINT `fk_movilidad_tbl_colegio1`
    FOREIGN KEY (`colegio_id`)
    REFERENCES `db_movilidad_escolar`.`tbl_colegio` (`colegio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movilidad_tbl_apoderado1`
    FOREIGN KEY (`apoderado_id`)
    REFERENCES `db_movilidad_escolar`.`tbl_apoderado` (`apoderado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movilidad_tbl_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `db_movilidad_escolar`.`tbl_grado` (`grado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movilidad_tbl_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `db_movilidad_escolar`.`tbl_vehiculo` (`vehiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movilidad_tbl_alumno1`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_movilidad_escolar`.`tbl_alumno` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
